apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/GithubID/yourRePo.git
    targetRevision: main
    path: 06-eks-istio-argocd-starbucks/argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
spec:
  source:
    repoURL: https://github.com/daeun-ops/terraform-playground.git
    targetRevision: main
    path: 06-eks-istio-argocd-starbucks/argocd/apps      
