tempo:
  repository: grafana/tempo
  fullnameOverride: tempo
  retention: 48h
  searchEnabled: true
  metricsGenerator:
    enabled: true
    remoteWriteUrl: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090/api/v1/write"
  storage:
    trace:
      backend: local
      wal:
        enabled: true
gateway:
  enabled: true
  service:
    type: ClusterIP
distributor:
  replicas: 1
ingester:
  replicas: 1
querier:
  replicas: 1
queryFrontend:
  replicas: 1
