loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  schemaConfig:
    configs:
    - from: 2024-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h
read:
  replicas: 1
write:
  replicas: 1
backend:
  replicas: 1
gateway:
  enabled: true
  service:
    type: ClusterIP
