tempo:
  repository: grafana/tempo
  fullnameOverride: tempo
  retention: 48h
  searchEnabled: true
  metricsGenerator:
    enabled: true
    remoteWriteUrl: "http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090/api/v1/write"
  storage:
    trace:
      backend: local
      wal:
        enabled: true
gateway:
  enabled: true
  service:
    type: ClusterIP
distributor:
  replicas: 1
ingester:
  replicas: 1
querier:
  replicas: 1
queryFrontend:
  replicas: 1
tempo:
  retention: 168h
  storage:
    trace:
      backend: s3
      s3:
        bucket: "starbucks-traces"                 # <<<<< S3 버킷명
        endpoint: "s3.ap-northeast-2.amazonaws.com"
        region: "ap-northeast-2"
        access_key: "${S3_ACCESS_KEY}"            # (Secret로 빼는 게 베스트)
        secret_key: "${S3_SECRET_KEY}"
        insecure: false
