apiVersion: batch/v1
kind: CronJob
metadata:
  name: ml-pipeline-trainer
  namespace: prod
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          priorityClassName: batch-ml
          topologySpreadConstraints:
          - maxSkew: 1
            topologyKey: topology.kubernetes.io/zone
            whenUnsatisfiable: ScheduleAnyway
            labelSelector:
              matchLabels: { app: ml-pipeline }
