apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: api
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames: ["prod"]
  selector:
    matchLabels: { app: api }
  podMetricsEndpoints:
  - port: http
    interval: 15s
